// Builds a random tone from the effect catalog, for quickly auditioning combinations.
// Values stay in musically usable ranges so a random tone is never unusable or painfully loud.

import { FX_BY_SLOT, fxInfo } from "./fx-catalog.js";
import { AMP_SLOT, AMP_PARAM, PEDAL_COUNT } from "./spark-preset.js";

// The J.H. (Hendrix) gear is a paid in-app purchase: included only if you own it.
const isPaid = (fx) => fx.tech.startsWith("JH.");

// Quietest master volume a random tone is allowed to use (bedroom level on a Spark 40).
export const MIN_MASTER = 0.25;

const pick = (list) => list[Math.floor(Math.random() * list.length)];
const between = (min, max) => Math.round((min + Math.random() * (max - min)) * 100) / 100;

// How often each slot is switched on, and the range its knobs are randomised within.
const SLOT_RULES = [
  { chance: 0.5, min: 0.05, max: 0.25 }, // 0 noise gate (high thresholds cut sustain)
  { chance: 0.3, min: 0.3, max: 0.7 },  // 1 compressor
  { chance: 0.6, min: 0.25, max: 0.75 }, // 2 drive
  { chance: 1.0, min: 0.35, max: 0.75 }, // 3 amp (always on)
  { chance: 0.35, min: 0.2, max: 0.6 },  // 4 modulation
  { chance: 0.45, min: 0.2, max: 0.6 },  // 5 delay
  { chance: 0.75, min: 0.15, max: 0.5 }, // 6 reverb
];

export function randomTone(baseTone, counter = 1, { includePaid = true } = {}) {
  const pedals = [];
  for (let slot = 0; slot < PEDAL_COUNT; slot++) {
    const rule = SLOT_RULES[slot];
    const options = (FX_BY_SLOT[slot] ?? []).filter((fx) => includePaid || !isPaid(fx));
    const choice = options.length ? pick(options) : null;
    const name = choice?.tech ?? baseTone?.pedals?.[slot]?.name ?? "";
    const info = fxInfo(name);
    const count = info?.params?.length ?? baseTone?.pedals?.[slot]?.parameters?.length ?? 0;

    const parameters = Array.from({ length: count }, (_, p) => {
      if (info?.selector === p) return pick(info.variants).value; // e.g. which reverb type
      return between(rule.min, rule.max);
    });
    if (slot === AMP_SLOT) {
      // Keep the amp's tone stack sane and the level steady, so tones stay comparable.
      parameters[AMP_PARAM.treble] = between(0.35, 0.7);
      parameters[AMP_PARAM.mid] = between(0.35, 0.7);
      parameters[AMP_PARAM.bass] = between(0.35, 0.7);
      // Follow the volume you were playing at, but never go so quiet that the
      // random tone can't be heard – then it looks like nothing changed.
      const inherited = baseTone?.pedals?.[AMP_SLOT]?.parameters?.[AMP_PARAM.master] ?? 0.6;
      parameters[AMP_PARAM.master] = Math.max(MIN_MASTER, inherited);
    }
    pedals.push({ name, isOn: Math.random() < rule.chance, parameters });
  }

  return {
    uuid: crypto.randomUUID().toUpperCase(),
    name: `Random ${counter}`,
    version: "0.7",
    description: "Generated by Spark Switch",
    icon: "icon.png",
    bpm: baseTone?.bpm ?? 120,
    pedals,
  };
}
